version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  allow:
    - dependency-type: "all"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - CeeBeeUK
  labels:
  - dependencies
  ignore:
  - dependency-name: acts_as_list
    versions:
    - "> 0.9.12"
  - dependency-name: foundation-rails
    versions:
    - "> 5.5.3.2"
- package-ecosystem: npm
  directory: "/"
  allow:
    - dependency-type: "all"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - CeeBeeUK
  labels:
  - yarn-dependencies
