version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - CeeBeeUK
  labels:
  - dependencies
  ignore:
  - dependency-name: acts_as_list
    versions:
    - "> 0.9.12"
  - dependency-name: factory_bot_rails
    versions:
    - "> 4.11.1"
  - dependency-name: foundation-rails
    versions:
    - "> 5.5.3.2"
  - dependency-name: rspec-rails
    versions:
    - 4.1.0
  - dependency-name: rubocop
    versions:
    - 1.9.0
  - dependency-name: omniauth
    versions:
    - 2.0.1
