version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  allow:
    - dependency-type: "all"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - CeeBeeUK
  labels:
  - dependencies
  groups:
    bundler:
      patterns:
        - '*'
  ignore:
    - dependency-name: acts_as_list
      versions:
      - "> 0.9.12"
    - dependency-name: foundation-rails
      versions:
      - "> 5.5.3.2"
- package-ecosystem: npm
  directory: "/"
  target-branch: main
  allow:
    - dependency-type: "all"
  schedule:
    interval: weekly
    day: friday
  open-pull-requests-limit: 10
  reviewers:
  - CeeBeeUK
  labels:
  - yarn-dependencies
  groups:
    node:
      patterns:
        - '*'
