version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  allow:
    - dependency-type: "all"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  reviewers:
  - CeeBeeUK
  labels:
  - dependencies
  groups:
    bundler:
      patterns:
        - '*'
  ignore:
    - dependency-name: foundation-rails
      versions:
      - "> 5.5.3.2"
    - dependency-name: rails
      versions:
        - ">= 8.0.0"
    - dependency-name: rails-i18n
      versions:
        - ">= 8.0.0"
    - dependency-name: railties
      versions:
        - ">= 8.0.0"
    - dependency-name: action*
      versions:
        - ">= 8.0.0"
    - dependency-name: active*
      versions:
        - ">= 8.0.0"
- package-ecosystem: npm
  directory: "/"
  target-branch: main
  allow:
    - dependency-type: "all"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  reviewers:
  - CeeBeeUK
  labels:
  - yarn-dependencies
  groups:
    node:
      patterns:
        - '*'
