inherit_from: .rubocop_todo.yml

plugins: rubocop-rspec

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - './*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'lib/demo_data/**/*'
    - 'lib/tasks/**/*'
    - 'features/**/*'
    - 'old_features/**/*'
    - 'spec/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 120

Style/FormatStringToken:
  EnforcedStyle: template
