language: ruby
sudo: false
rvm:
- 2.6.3
cache: bundler
services:
- postgresql
before_install:
- gem update --system
- gem install bundler
- yarn --version
- yarn
before_script:
- psql -c 'create role euro login createdb;' -U postgres
addons:
  postgresql: 9.6
  code_climate:
    repo_token: 352f320ede2f679be5d89f246dc321cea7839db59bfe0b9d88c5de5c90505e53
script:
- bundle exec rake db:create
- bundle exec rake db:migrate
- bundle exec rake db:seed
- bundle exec rake spec
- bundle exec rake rubocop
deploy:
  provider: heroku
  api_key:
    secure: A9GCya6Hna63zMi4rBRZ3tx6KTrpffZOuzOJA3dnEYKRoBv7Ri+0Hg8QoN466zuyBdIZpRdyTJAQYqM6R8GlR2E/bRkzeZojk8SYqcAZtLXxqRmuz1NRLlUUnjGiCRhGYOIp4Y49bmbYVg6dfh0G1frtxyVtDH/UJdymR9DEGQc=
  app: laughing-sansa
  on:
    repo: CeeBeeUK/laughing-sansa
after_success:
- bundle exec codeclimate-test-reporter