name: Docker
on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  push-store-image:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
  
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
  
      - name: 'Build Inventory Image'
        run: |
          docker build . --tag ghcr.io/${{github.actor}}/${{ github.repository }}/eurovision:latest
          docker push ghcr.io/${{github.actor}}/${{ github.repository }}/eurovision:latest
